"""
Django settings for Motoris project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib import messages
# envから引っ張ってくるよう
from dotenv import load_dotenv
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-km^!v%bgimbr398&&3tx=5mmvc^pn6)=q8xuppqb2^&c9&4=*s'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG:False時,python manage.py collectstatic
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'motoris.f5.si']
# slash自動補完false
# APPEND_SLASH = False
# csrfするdomain
CSRF_TRUSTED_ORIGINS = [
    "https://motoris.f5.si",
]


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'shuppin.apps.ShuppinConfig',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.sites',  # 必須: django-allauth
    
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Googleログイン用
    
    'events.apps.EventsConfig',
    'profiles.apps.ProfilesConfig',
    'markets.apps.MarketsConfig',
    'shohin.apps.ShohinConfig',
    'searches.apps.SearchesConfig',
    'purchase.apps.PurchaseConfig',
    'widget_tweaks',
    'formpage.apps.FormpageConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Motorisを削除(Motoris.config~から)
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                    BASE_DIR / 'templates',
                    BASE_DIR / 'templates_allauth',  # カスタムテンプレート用フォルダ
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.settings.global_settings',  # envのグローバル変数を定義
            ],
        },
    },
]
# Motorisを削除(Motoris.config~から)
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

#登録パスワードバリデーション
AUTH_PASSWORD_VALIDATORS = [
    {   #メルアドににpw拒否
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {   #パスワードの最小文字数(デフォルト8文字)を指定
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {   #一般的なpwを拒否(password123など)
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {   #数字だけのpw拒否
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# ユーザーモデルカスタムモデル使用(メルアドユニークさせるため)
AUTH_USER_MODEL = 'accounts.CustomUser'



# カスタム認証バックエンドをDjangoに追加
AUTHENTICATION_BACKENDS = [
    # アプリ名.ファイル名(.py無し).class名
    'accounts.tuika.EmailOrUsernameBackend',  # カスタム認証バックエンド
    'django.contrib.auth.backends.ModelBackend',  # デフォルトの認証バックエンド
    'allauth.account.auth_backends.AuthenticationBackend',  # django-allauth
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

SITE_ID = 1

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# スタティックurlパス
STATIC_URL = '/static/'
# 開発環境時のスタティックの居場所
STATICFILES_DIRS = [BASE_DIR / 'static',]
# 本番環境時のスタティックの場所
STATIC_ROOT =os.path.join( BASE_DIR / 'staticfiles')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login, Logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# LoginのURLを指定(LoginRequiredMixinで未ログイン時のとび先)
LOGIN_URL = '/login/'


# カスタム404エラーページを使う設定
# defはtopのview、htmlはtemplateのbaseと同じ
handler404 = 'top.views.custom_404_view'


# メール送信用

# Mail
# djangoが外部のメール送信バックエンドを指定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 使用するsmtpサーバーはグーグル
EMAIL_HOST = 'smtp.gmail.com'
# ポートはtlsの587を指定
EMAIL_PORT = 587
# tlsをtrueに
EMAIL_USE_TLS = True
# smtpにログインするアドレス(送信元としても使用)
EMAIL_HOST_USER = 'NH24.IAIH.J@gmail.com'
# smtpログイン用のアプリパスワード
EMAIL_HOST_PASSWORD = 'gkxc hqkp vlvv rxiz'

# Allauth の設定
# 自動サインアップを有効化(初ソーシャルログイン時アカウント作成)
SOCIALACCOUNT_AUTO_SIGNUP = True
# GETリクエストで即ログイン(確認画面経由しない)
SOCIALACCOUNT_LOGIN_ON_GET = True
# ソーシャルログインでで必要な情報
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            # 認証情報
            'client_id': '46444256099-leo84chkvmptea4batcfsjv6uhdghuqq.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        # グーグルアカウントからユーザープロフィールやメールアドレスを引っ張てくる
        'SCOPE': ['profile', 'email'],
        # トークンが有効のみ認証
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
# ソーシャルアカウントのログイン用のアダプターの設定
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.MySocialAccountAdapter'
# messagetagに応じたbootstrap
MESSAGE_TAGS = {
    messages.INFO: 'alert alert-info',
    messages.SUCCESS: 'alert alert-success',
    messages.WARNING: 'alert alert-warning',
    messages.ERROR: 'alert alert-danger',
}
# 環境変数読取
load_dotenv()  # .envを読み込む
# それぞれenvから取得
CHATGPT_API_KEY = os.getenv("ChatGptAPIKey")
DEEPL_API_KEY = os.getenv("DeeplAPIkey")
# グローバルとして定義
def global_settings(request):
    return {
        'CHATGPT_API_KEY': settings.CHATGPT_API_KEY,
        'DEEPL_API_KEY': settings.DEEPL_API_KEY,
    }
    

